/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'on-secondary-container': '#b6b8c1',
        'on-secondary-fixed-variant': '#44474e',
        'surface-dim': '#0c0e14',
        'outline': '#988e90',
        'background': '#000000',
        'surface': '#0c0e14',
        'surface-bright': '#383940',
        'surface-container-low': '#1a1b22',
        'on-error-container': '#ffdad6',
        'surface-container-high': '#282a31',
        'secondary-fixed': '#e1e2eb',
        'inverse-on-surface': '#2f3037',
        'tertiary-fixed': '#e2e2e2',
        'surface-tint': '#c6c6c6',
        'inverse-surface': '#e2e1eb',
        'secondary-fixed-dim': '#c4c6cf',
        'primary-fixed': '#e2e2e2',
        'primary-container': '#000000',
        'secondary-container': '#464950',
        'primary': '#0070F3',
        'on-primary-fixed-variant': '#474747',
        'error-container': '#93000a',
        'surface-container-lowest': '#0c0e14',
        'on-error': '#690005',
        'secondary': '#c4c6cf',
        'outline-variant': 'rgba(255,255,255,0.08)',
        'on-tertiary': '#303030',
        'on-surface-variant': '#cfc4c5',
        'surface-container': '#1e1f26',
        'inverse-primary': '#5e5e5e',
        'on-primary-container': '#757575',
        'on-secondary-fixed': '#191c22',
        'on-background': '#e2e1eb',
        'on-secondary': '#2e3037',
        'tertiary-container': '#000000',
        'surface-variant': '#33343c',
        'on-tertiary-fixed': '#1b1b1b',
        'on-tertiary-container': '#757575',
        'tertiary-fixed-dim': '#c6c6c6',
        'tertiary': '#c6c6c6',
        'primary-fixed-dim': '#c6c6c6',
        'surface-container-highest': '#33343c',
        'on-surface': '#e2e1eb',
        'on-primary': '#FFFFFF',
        'on-tertiary-fixed-variant': '#474747',
        'on-primary-fixed': '#1b1b1b',
        'error': '#ffb4ab',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'section-gap-lg': '160px',
        'unit': '4px',
        'section-gap-md': '80px',
        'margin-desktop': '64px',
        'gutter': '24px',
        'margin-mobile': '20px',
        'container-max': '1200px',
      },
      fontFamily: {
        'body-lg': ['Inter', 'sans-serif'],
        'headline-md': ['Hanken Grotesk', 'sans-serif'],
        'headline-lg': ['Hanken Grotesk', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'display-lg': ['Hanken Grotesk', 'sans-serif'],
        'label-sm': ['Geist', 'monospace'],
        'headline-lg-mobile': ['Hanken Grotesk', 'sans-serif'],
        'label-md': ['Geist', 'monospace'],
      },
      fontSize: {
        'body-lg': ['18px', { lineHeight: '1.6', letterSpacing: '0em', fontWeight: '400' }],
        'headline-md': ['32px', { lineHeight: '1.3', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-lg': ['48px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '1.6', letterSpacing: '0em', fontWeight: '400' }],
        'display-lg': ['72px', { lineHeight: '1.1', letterSpacing: '-0.04em', fontWeight: '700' }],
        'label-sm': ['12px', { lineHeight: '1.4', letterSpacing: '0.05em', fontWeight: '500' }],
        'headline-lg-mobile': ['32px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '600' }],
        'label-md': ['14px', { lineHeight: '1.4', letterSpacing: '0.02em', fontWeight: '500' }],
      },
      maxWidth: {
        'container-max': '1200px',
      },
    },
  },
  plugins: [],
}
